### ISSUE TITLE
Application not run windows 10

### ISSUE THREAD

**Issue by aboobakkar** [scottmcallister/auth-app#1]
i am already installed meteor windows installer, node js stable version, git asap
i try your readme content ..
meteor npm install sucesfully added.
then type  "meteor" .. downloading meteor 1.3 packages as running task infinitly.. 
But this same task worked for Windows 7 Os.. What is is the actual issue ?
![aserror](https://cloud.githubusercontent.com/assets/6416738/20638869/2f5a7540-b3d9-11e6-9333-448421766ba0.png)

**Comment by scottmcallister** [comment]
I haven't tried installing Meteor on Windows myself, but if you aren't able to extract the dependencies I'm thinking there may be an issue with the Meteor installation on your system. Do you have [7-Zip](http://www.7-zip.org/) installed? Has the Meteor installation archive been added to your `PATH`? 

You can try installing Meteor without the Windows installer:
[https://github.com/meteor/docs/blob/version-NEXT/long-form/alternate-windows-installation.md](https://github.com/meteor/docs/blob/version-NEXT/long-form/alternate-windows-installation.md)
